/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAlert: typeof import('./src/components/App/Alert.vue')['default']
    AppButton: typeof import('./src/components/App/Button.vue')['default']
    AppEmptyState: typeof import('./src/components/App/EmptyState.vue')['default']
    AppErrorState: typeof import('./src/components/App/ErrorState.vue')['default']
    AppInput: typeof import('./src/components/App/Input.vue')['default']
    AppSelect: typeof import('./src/components/App/Select.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    RepoCard: typeof import('./src/components/Repo/Card.vue')['default']
    RepoList: typeof import('./src/components/Repo/List.vue')['default']
    RepoPagination: typeof import('./src/components/Repo/Pagination.vue')['default']
    RepoSearchForm: typeof import('./src/components/Repo/SearchForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
